### ISSUE TITLE
FParsec operators

### ISSUE THREAD

**Issue by amazingant** [fsharp/vim-fsharp#20]
Going to add some FParsec operators and make a pull-request for it when I get a chance, as suggested by @kjnilsson

Full list of FParsec's operators taken from [their documentation(http://www.quanttec.com/fparsec/reference/primitives.html#interface) is:

* `>>=`
* `>>.`
* `.>>`
* `.>>.`
* `|>>`
* `<|>`
* `<|>%`
* `>>=?`
* `>>?`
* `.>>?`
* `.>>.?`
* `<?>`
* `<??>`

Any of these I should _**not**_ add?

**Comment by kjnilsson** [comment]
looks fine to me

**Comment by kjnilsson** [comment]
@amazingant do you want me to keep this open?

**Comment by amazingant** [comment]
Sorry, I ran into some issues partway through add the operators and got distracted by something at work; completely forgot I was working on this. If I get a chance to get back to it, I'll open a pull request then.
