### ISSUE TITLE
Cygwin support

### ISSUE THREAD

**Issue by yever** [fsharp/vim-fsharp#31]
I've been mostly using gVim on Windows, but it's no to be able to use native vim on Cygwin without having to open an external window. 

The main issue is that the paths to fsautocomplete, fsi and msbuild are passed Windows-style, but Cygwin's bash can't handle them. To transform the path, Cygwin provides a CLI utility: `cygpath`.

**Comment by yever** [comment]
This is trickier than I thought... There's a lot of back-and-forth conversions required here. I'm trying to look for a way to keep conversions to a minimum.

**Comment by kjnilsson** [comment]
I'm wondering if it's worth the effort to support cygwin.
