### ISSUE TITLE
Omnicomplete isn't working on osx

### ISSUE THREAD

**Issue by naveensrinivasan** [fsharp/vim-fsharp#37]
The Omnicomplete isn't working.

<img width="1257" alt="screen shot 2015-12-28 at 5 11 34 pm" src="https://cloud.githubusercontent.com/assets/172697/12026334/387e44bc-ad86-11e5-8eac-4fc55534f783.png">

I am getting other errors.  I do have `supertab` and `syntastic`

>➜  bundle git:(master) ✗ mono --version
>Mono JIT compiler version 4.2.0 (Stable 4.2.0.179/a224653 Tue Oct  6 11:28:25 PDT 2015)
>Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
>	TLS:           normal
>	SIGSEGV:       altstack
>	Notification:  kqueue
>	Architecture:  amd64
>	Disabled:      none
>	Misc:          softdebug
>	LLVM:          supported, not enabled.
>	GC:            sgen

How do I debug what the issue is?

Thank you!

**Comment by kjnilsson** [comment]
what supertab config do you have?

**Comment by naveensrinivasan** [comment]
I have the default supertab. Is there something specific that I should enable?

**Comment by kjnilsson** [comment]
I have also noticed that I often fail to get completion for names in the local scope - do you think this would be indicative of not using fsac correctly in vim-fsharp @rneatherway ?

**Comment by rneatherway** [comment]
It sounds very plausible that there could be an off-by-1 error or something like that. If you can post a log of the two-way communication when you don't get what you expect (the whole session including parse commands etc) then I can have a look.

**Comment by kjnilsson** [comment]
hmm weirdly it started working again after a vim restart. I'll keep an eye on it and will raise a bug when I can reliably reproduce. Thanks.

**Comment by naveensrinivasan** [comment]
I tried this setting to get the debug `let g:fsharpbinding_debug = 1` but I couldn't find any log files in the tmp folder. Is there anything else that am I missing?

**Comment by kjnilsson** [comment]
Ok I've just pushed an update that uses the filter option in fsac. Could
you get the latest and try again?

**Comment by naveensrinivasan** [comment]
No that didn't help either. I am not seeing log files in the temp folder either.

**Comment by kjnilsson** [comment]
Strange you aren't getting any logs. Do you get any completions after say 'List.'?

**Comment by kjnilsson** [comment]
Also try executing :FSharpLogFile in vim and check the full path to the log file.

**Comment by naveensrinivasan** [comment]
No I ran into this error
>Error detected while processing function fsharpbinding#python#LoadLogFile:
>line    3:
>Traceback (most recent call last):
>  File "<string>", line 1, in <module>
>AttributeError: FSAutoComplete instance has no attribute 'logfiledir'

**Comment by naveensrinivasan** [comment]
This is `scriptnames` output if that would help
>  1: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/vimrc
>  2: ~/.vimrc
>  3: ~/.vim/autoload/pathogen.vim
>  4: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/ftoff.vim
>  5: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/filetype.vim
>  6: ~/.vim/bundle/Dockerfile/ftdetect/Dockerfile.vim
>  7: ~/.vim/bundle/fsharpbinding-vim/ftdetect/fsharp.vim
>  8: ~/.vim/bundle/vim-fsharp/ftdetect/fsharp.vim
>  9: ~/.vim/bundle/vim-git/ftdetect/git.vim
> 10: ~/.vim/bundle/vim-ps1/ftdetect/ps1.vim
> 11: ~/.vim/bundle/vim-ps1/ftdetect/ps1xml.vim
> 12: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/menu.vim
> 13: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/autoload/paste.vim
> 14: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/ftplugin.vim
> 15: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/indent.vim
> 16: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/syntax/syntax.vim
> 17: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/syntax/synload.vim
> 18: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/syntax/syncolor.vim
> 19: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/syntax/nosyntax.vim
> 20: ~/.vim/bundle/badwolf/colors/badwolf.vim
> 21: ~/.vim/bundle/fugitive/plugin/fugitive.vim
> 22: ~/.vim/bundle/supertab/plugin/supertab.vim
> 23: ~/.vim/bundle/syntastic/plugin/syntastic/autoloclist.vim
> 24: ~/.vim/bundle/syntastic/plugin/syntastic/balloons.vim
> 25: ~/.vim/bundle/syntastic/plugin/syntastic/checker.vim
> 26: ~/.vim/bundle/syntastic/plugin/syntastic/cursor.vim
> 27: ~/.vim/bundle/syntastic/plugin/syntastic/highlighting.vim
> 28: ~/.vim/bundle/syntastic/plugin/syntastic/loclist.vim
> 29: ~/.vim/bundle/syntastic/plugin/syntastic/modemap.vim
> 30: ~/.vim/bundle/syntastic/plugin/syntastic/notifiers.vim
> 31: ~/.vim/bundle/syntastic/plugin/syntastic/registry.vim
> 32: ~/.vim/bundle/syntastic/plugin/syntastic/signs.vim
> 33: ~/.vim/bundle/syntastic/plugin/syntastic.vim
> 34: ~/.vim/bundle/syntastic/autoload/syntastic/util.vim
> 35: ~/.vim/bundle/vim-airline/plugin/airline.vim
> 36: ~/.vim/bundle/vim-airline/autoload/airline.vim
> 37: ~/.vim/bundle/vim-airline/autoload/airline/init.vim
> 38: ~/.vim/bundle/vim-airline/autoload/airline/parts.vim
> 39: ~/.vim/bundle/vim-fugitive/plugin/fugitive.vim
> 40: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/plugin/getscriptPlugin.vim
> 41: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/plugin/gzip.vim
> 42: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/plugin/logiPat.vim
> 43: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/plugin/matchparen.vim
> 44: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/plugin/netrwPlugin.vim
> 45: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/plugin/rrhelper.vim
> 46: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/plugin/spellfile.vim
> 47: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/plugin/tarPlugin.vim
> 48: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/plugin/tohtml.vim
> 49: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/plugin/vimballPlugin.vim
> 50: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/plugin/zipPlugin.vim
> 51: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/gvimrc
> 52: ~/.vim/bundle/vim-airline/autoload/airline/extensions.vim
> 53: ~/.vim/bundle/vim-airline/autoload/airline/extensions/quickfix.vim
> 54: ~/.vim/bundle/vim-airline/autoload/airline/extensions/netrw.vim
> 55: ~/.vim/bundle/vim-airline/autoload/airline/extensions/branch.vim
> 56: ~/.vim/bundle/vim-airline/autoload/airline/extensions/syntastic.vim
> 57: ~/.vim/bundle/vim-airline/autoload/airline/extensions/whitespace.vim
> 58: ~/.vim/bundle/vim-airline/autoload/airline/extensions/wordcount.vim
> 59: ~/.vim/bundle/vim-airline/autoload/airline/section.vim
> 60: ~/.vim/bundle/vim-airline/autoload/airline/highlighter.vim
> 61: ~/.vim/bundle/vim-airline/autoload/airline/themes/badwolf.vim
> 62: ~/.vim/bundle/vim-airline/autoload/airline/themes.vim
> 63: ~/.vim/bundle/vim-airline/autoload/airline/util.vim
> 64: ~/.vim/bundle/vim-airline/autoload/airline/builder.vim
> 65: ~/.vim/bundle/vim-airline/autoload/airline/extensions/default.vim
> 66: ~/.vim/bundle/syntastic/autoload/syntastic/log.vim
> 67: ~/.vim/bundle/vim-airline/autoload/airline/deprecation.vim
> 68: /usr/local/Cellar/macvim/7.4-81/MacVim.app/Contents/Resources/vim/runtime/scripts.vim
> 69: ~/.vim/bundle/fsharpbinding-vim/ftplugin/fsharp.vim
> 70: ~/.vim/bundle/vim-fsharp/ftplugin/fsharp.vim
> 71: ~/.vim/bundle/fsharpbinding-vim/syntax/fsharp.vim
> 72: ~/.vim/bundle/vim-fsharp/syntax/fsharp.vim
> 73: ~/.vim/bundle/fsharpbinding-vim/syntax_checkers/fsharp/syntax.vim
> 74: ~/.vim/bundle/vim-fsharp/syntax_checkers/fsharp/syntax.vim

**Comment by kjnilsson** [comment]
I wonder if the old fsharpbinding-vim install is interfering. Can you try
removing it?

**Comment by naveensrinivasan** [comment]
No, I am getting this

Error detected while processing function fsharpbinding#python#LoadLogFile:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: FSAutoComplete instance has no attribute 'logfiledir'
Press ENTER or type command to continue

**Comment by naveensrinivasan** [comment]
How is this happening `FSAutoComplete instance has no attribute 'logfiledir'` ?

**Comment by kjnilsson** [comment]
Did you try to remove the fsharpbinding-vim folder in your bundle directory?

**Comment by kjnilsson** [comment]
the only reason I can thing for this is that the old fsharpbinding-vim install is interfering and causeing issues. fsharpbinding-vim is deprecated and shouldn't be used anymore.

**Comment by naveensrinivasan** [comment]
I am out on vacation. When I get back will pick it up. Thanks!

**Comment by kjnilsson** [comment]
@naveensrinivasan any progress on this? does the issue need to stay open?

**Comment by naveensrinivasan** [comment]
Sorry I have moved out of writing code in .NET and F#. So I am going to close it.
