### ISSUE TITLE
neovim support

### ISSUE THREAD

**Issue by xajler** [fsharp/vim-fsharp#40]
Not sure if `vim-sharp` is supported hosted in `neovim`, maybe this is problem.

I've installed `vim-sharp`, `supertab`, `syntastic`, all by `vim-plug`, and added code needed to load it only for fsharp.
I've also ran `install.sh` in `vim-fsharp`, provided `xbuild` path in `.vimrc`, but each time I open .fs file that is actually part of .fsproj or any other .fs(x) file, I'm not getting no command like `:FSBuildProject`, and it doesn't recognizes any `:FS*` command.

I can see that requirement is `vim 7.3` and `python`. I have installed `python 2.7.11`. And latest `neovim 0.1.2`, both `python` and `neovim` compiled from source with `Homebrew` on latest Mac OS X El Capitan.

If is the problem with having it running from `neovim`, will there be any support for `neovim`?
Or if anybody have any experience with `neovim` and `vim-fsharp`, do you know how to set it up properly?

Thanks

**Comment by kjnilsson** [comment]
Hi - I have never tried neovim and I am not sure what is involved in getting it to work there. Does neovim interpret vimscrip?

**Comment by xajler** [comment]
Thanks for reply. From what I know it is, they'll use lua in future, but this is still not implemented. 

For example `fzf.vim` is written completely in vimL/vimscript and like `vim-plug` works without any problem, I also get tab completion, but only for the words in current document. 

Probably something else is problem maybe python, to bad I don't know how to get any logs (if any) to see where things go wrong, or is there is any way to investigate what is going wrong?

**Comment by kjnilsson** [comment]
you could try enabling debug in here: https://github.com/fsharp/vim-fsharp#settings

not sure it will tell you much though.

**Comment by xajler** [comment]
Found out what was the problem, so if any will have a problem in future.
To run python plugins in `neovim` there is need to install `pip` package `neovim`.
But seems that this is a problem in El Capitan outside of `virtualenv` because of Mac system integrity checks or whatever is called.
But it can be installed with `--user` switch.

`pip install --user  neovim`

Now loading is significantly slower, when I open F# file, but it works with neovim!
Thanks again @kjnilsson 

![screen shot 2016-02-15 at 11 21 04](https://cloud.githubusercontent.com/assets/40003/13045990/92981254-d3d6-11e5-8ccc-8cb01a46f593.png)

**Comment by kjnilsson** [comment]
Oh great! :) yes first load is always slow due to having to wait for the
background process to start. After that it should be less slow to open new
fsharp files (hopefully).

**Comment by kjnilsson** [comment]
so can we close this issue now?

**Comment by xajler** [comment]
Yes, sure
