### ISSUE TITLE
Option 'omnifunc' not set on Linux

### ISSUE THREAD

**Issue by spencerwi** [fsharp/vim-fsharp#42]
Launching Vim and editing an FSharp file with this plugin installed launches a background fsautocomplete process, which is to be expected.

Subsequently exiting vim leaves the fsautocomplete process still running, which is not to be expected.

The net result is that if I follow a common loop of "edit->:wq->test, edit->:wq->test" I could wind up with many background fsautocomplete processes hanging around chewing up system resources.

**Comment by kjnilsson** [comment]
Hi,

I can't reproduce this on OSX. Can you provide some more detail on the environment you are using?

Because the first parse is so slow I wouldn't recommend a workflow with transient vim sessions. I tend to have a split screen setup with vim left open.

Thanks

**Comment by spencerwi** [comment]
Well, admittedly, after updating I can no longer reproduce it on my linux box, but now I'm also not getting any autocomplete; none of the "FSharp...." commands are defined and `Ctrl-X Ctrl-O` (triggering omnicomplete) just says `Option 'omnifunc' not set!`

**Comment by kjnilsson** [comment]
how are you installing it?

**Comment by spencerwi** [comment]
Aaaand I purged it and reinstalled it and now it works. I did have a leftover `fsharpbinding/` folder in `bundle/`, which looks from other issues like it can cause problems.

**Comment by kjnilsson** [comment]
Ah yes fsharpbinding leftovers have caused very weird issues in the  past.
:)

**Comment by spencerwi** [comment]
Whoops, sorry, deleted last comment by mistake; it was:

> And I purged and reinstalled and now it works. I did have a leftover `fsharpbinding/` folder in `bundle/`, which I've read in other issues can cause problems.

**Comment by spencerwi** [comment]
Looks like I spoke too soon: 

https://asciinema.org/a/5he42yb79h8ve6tke5u4c4i32

Not sure why I had an intermittent case where it worked once after purge/reinstall, and hasn't worked again.

**Comment by kjnilsson** [comment]
Sorry. Not sure what it is that isn't working on that video.

**Comment by spencerwi** [comment]
I open an FSharp source file, and trigger omnicomplete. Nothing happens except `Option 'omnifunc' is not set`.

**Comment by kjnilsson** [comment]
did you run make install after the re-install? I take it yo are using plain
pathogen and none of the other bundlers?

**Comment by spencerwi** [comment]
I'm using Vim-Plug, and have it configured as per the README here, but I figured a `make install` is worth a shot.

https://asciinema.org/a/8f08a88c61y1qtt4997vnbbhk

Still no luck (notice the vim statusbar stating `Option 'omnifunc' not set`).

**Comment by kjnilsson** [comment]
ah - ok so it seems like the fake script is broken - I don't use that
myself and I am not sure what it is doing. the current strategy is to just
git clone vim-fsharp to the bundle directory and run 'make'.

**Comment by spencerwi** [comment]
Still not working for me. Bummer. Not sure what changed, but hopefully it'll work again in the future.

Thanks for your help.

**Comment by kjnilsson** [comment]
when did you last update? - very little has changed in the last few months.

**Comment by spencerwi** [comment]
Prior to the update (yesterday) that triggered my current set of
remove-reinstall-check cycles, I'd only had vim-fsharp installed for about
two months. I did, however, also update Vim-Plug, so it's possible that the
fault lies there instead.

**Comment by spencerwi** [comment]
Okay, I've figured out why it worked briefly and then stopped again.

Something about the plugin seems to be very path-dependent; it works when I launch vim from inside of my `$HOME/.vim` directory, but outside of that it doesn't do anything.

I setting `let g:fsharpbinding_debug = 1` in my `.vimrc`, but the debug log files never appeared in `/tmp/`.

**Comment by spencerwi** [comment]
Nope, I was wrong -- the issue is not with running it from inside `$HOME/.vim`, but with how I load the file.

* If I open vim and then `:e /the/full/path/to/my/file.fsx`, then fsharp-vim works (omnicomplete is set, the various commands are registered).
* If I open vim from inside `/the/full/path/to/my/` and then `:e file.fsx`, then fsharp-vim works.
* If I open vim by running `vim /the/full/path/to/my/file.fsx` from the command-line, then fsharp-vim doesn't work (omnicomplete not set, no commands registered).
* If I open vim from inside `/the/full/path/to/my` by running `vim file.fsx`, then fsharp-vim doesn't work.

**Comment by kjnilsson** [comment]
Ah ok - so there is a genuine issue there - I can't replicate it on osx
however - which version of vim are you on?

**Comment by spencerwi** [comment]
I've tried it with current NeoVim and with vanilla Vim 7.4.712, both on Ubuntu 15.10 (wily)

**Comment by kjnilsson** [comment]
i'm on 7.4 as well and can do vim test.fsx quite nicely without any issues
- I wonder what is different.

**Comment by austincrft** [comment]
Just to chime in, running Arch I don't see this issue on NeoVim 0.1.5 or Vim 7.4.

**Comment by kjnilsson** [comment]
@spencerwi do we need to keep this open?

**Comment by spencerwi** [comment]
I still have trouble with it at times, but since it seems like others are not hitting the issue, I'm leaning towards an issue with my own system. No need to keep this open, then.

**Comment by spencerwi** [comment]
Also, I just connected the dots that I've talked to you on the FP slack. Hi again!

**Comment by kjnilsson** [comment]
Hi, and thanks!
