### ISSUE TITLE
E492: Not an editor command: FsiShow

### ISSUE THREAD

**Issue by fjoppe** [fsharp/vim-fsharp#43]
I did follow all the instructions in the [readme](https://github.com/fsharp/vim-fsharp/blob/master/README.mkd). I installed pathogen, syntastic, vim-plug and I cloned this repo in "~/.vim/bundle" folder and ran "make".

When I open an .fsx, I see syntax highlighting. However, the commands are not working. `:FsiShow` gives the error in the title. All other commands (except "make") give the same error.

This command from syntastic does work: `:Helptags`
This command from vim-plug does work: `:PlugInstall`

I was actually interested in using vim with the FSI (hopefully it gives some performance benefits).

vim version: 7.4.1689
Runs on Ubuntu 16.04 LTS

**Comment by wewebber** [comment]
Do you have Python supported compiled into vim?  Do

    :echo has('python')

Note that you need python, not python3.

**Comment by fjoppe** [comment]
Hi, that command in vim returns "0" (I don't know what that means). In bash "python --version" returns "Python 2.7.11+".

**Comment by wewebber** [comment]
"0" means you don't have python support compiled in.

Inside vim, type ":version".  It should tell you all the compile-time options.

What system are you on?  Have you installed vim from a package manager or in some other way?

**Comment by fjoppe** [comment]
Hi, I'm running vim on a clean install of Ubuntu 16.04 LTS server.

**Comment by wewebber** [comment]
Ah, ok, probably the same issue I came across, then.

vim-fsharp requires Python2, but the default install of vim on Ubuntu 16.04 is compiled against Python3.

If you're using vim in the terminal, then do:

     sudo apt install vim-nox-py2

If you're using gvim, there should likewise be a "py2" variant.

**Comment by fjoppe** [comment]
Hi, that worked, thanks!
It does have some issues, `Alt+Enter` does not work while `leader<i>` does. But surely getting further now.

**Comment by wewebber** [comment]
Great, glad that helped!

I'm using vim-fsharp inside tmux with a separate pane holding the fsharp interpreter.  Not as seamless as an in-IDE REPL but it works ok.

**Comment by kjnilsson** [comment]
@fjoppe I think the Alt-Enter binding was removed as it only worked on non terminal vim instances (or something). Thanks for your help @wewebber

**Comment by kjnilsson** [comment]
@fjoppe do we need to keep this issue open further?

**Comment by fjoppe** [comment]
No you can close it.

**Comment by kjnilsson** [comment]
thanks

**Comment by spencerwi** [comment]
It's probably worth noting in the README that python2 support is required. People using Python 3 are likely to hit confusing issues.

**Comment by kjnilsson** [comment]
done
