### ISSUE TITLE
autoindent isn't working

### ISSUE THREAD

**Issue by martindemello** [fsharp/vim-fsharp#44]
Using vim 7.4, plugin installed from git via vundle. If I type, e.g.

```
for x = 1 to 10 do
```

the next line does not indent either when I hit the enter key or when I try manually indenting it via `=`. Hitting enter always takes me to position 0 in the line, and hitting = always indents the line to the same depth as the previous line.

**Comment by kjnilsson** [comment]
vim-fsharp doesn't have any indentation support. PRs welcome. :)

**Comment by kjnilsson** [comment]
Indent support added.
