### ISSUE TITLE
[MacVim - ElCapitan] No commands

### ISSUE THREAD

**Issue by k0pernicus** [fsharp/vim-fsharp#49]
Hello guys!
I just installed the plugin in my `.vim` directory, but I can't use commands from this plugin...
I tried an `:FsiEval` on a simple code line, and Macvim said to me that `Not an editor command: FsiEval`.

MacVim doesn't support `Python`, only `Python3`. Anybody here using MacVim can just tell me how to install the `Python` support, without reinstalling the editor please?

Thanks!

**Comment by kjnilsson** [comment]
it needs to go into .vim/bundle and you need to run `make` before it will work. Did you follow the installation instructions? Also have you got pathogen installed?

**Comment by k0pernicus** [comment]
Yep.
I just tried again `make` but I have:
```
Air:vim-fsharp me$ make
make: Nothing to be done for `fsautocomplete'.
```

**Comment by k0pernicus** [comment]
I reinstalled entirely MacVim using `--with-python` and it works now.  
Unfortunately, I have an error using the checker with `open System.Net` - weird because I can use this lib in `fsharpi`...
