### ISSUE TITLE
[MacVim] Troubles with linter

### ISSUE THREAD

**Issue by k0pernicus** [fsharp/vim-fsharp#50]
I use MacVim with Python support.
When I try to write `open System.Net`, the linter (or something else) returns: `The namespace 'Net' is not defined`.
When I try the same thing using `fsharpi`, it works...

Is a configuration is required to use the plugin?

**Comment by kjnilsson** [comment]
Are you using an fs or fsx file? Can you post a full example? Does
autocompletion work?

**Comment by k0pernicus** [comment]
It's a `fs` file.

A simple example:

```
open System.IO //It works
open System.Net //It doesn't works

let fetch (s: string) : string =
    "Hello world"
```

**Comment by kjnilsson** [comment]
Have you got a project file?

**Comment by k0pernicus** [comment]
No, I thought that a `.fs` file was enough... :-/

**Comment by kjnilsson** [comment]
no it won't know to include System.Net - either switch to fsx and use `#r "System.Net"` or similar or add a project file with the appropriate references.

**Comment by k0pernicus** [comment]
Thanks,

Ok so move my file `ex.fs` to `ex.fsx` makes the program ok, without `#r "System.Net"`.  
I will check how to write some classes using `.fs` extensions (without scripting) and use `System.Net` for that...
