### ISSUE TITLE
Project file is "project.json" for dotnet core

### ISSUE THREAD

**Issue by tunz** [fsharp/vim-fsharp#51]
When I reference a module written in other files, The vim-fsharp throws an error:
```F#
open Game
```
```
The namespace or module 'Game' is not defined
```
I think it happens because dotnet includes files with `project.json` instead of `.fsproj` file. 
```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true,
    "compilerName": "fsc",
    "compile": {
      "includeFiles": [
        "Game.fs",
        "Program.fs"
      ]
    }
  },
...
```

**Comment by kjnilsson** [comment]
Correct. the version of the completion server we're using doesn't support the project.json format. There is basic support available now but it is untested and would need to be implemented in the vim plugin.

**Comment by austincrft** [comment]
So I've been working on this a little on [my fork](https://github.com/austincrft/vim-fsharp/tree/feature/dotnetcore-support). It looks like dotnet-core isn't working properly in [version 0.29.0](https://github.com/fsharp/FsAutoComplete/releases/tag/0.29.0) of FsAutoComplete, but I did get it to work after they updated the version of F#.

Unfortunately, this hasn't been cut to a release yet, so I think we'll have to wait until a new release is cut.

**Comment by kjnilsson** [comment]
@austincrft once you think it may be working ok I'm more than happy to test and accept a PR for that :)

**Comment by austincrft** [comment]
The `project.json` file won't be supported in further releases of dotnet core. See the [.NET Blog's Changes to Project.json](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) or [this StackOverflow answer](http://stackoverflow.com/a/38537047/3661319). 

With this knowledge, I think we should close this as `Won't Fix`.

**Comment by kjnilsson** [comment]
Ok this should now work in the latest master, you will need to use `make git` instead of just `make` when installing fsac.
