### ISSUE TITLE
Using MS distribution of F# instead of Mono. 

### ISSUE THREAD

**Issue by Tombert** [fsharp/vim-fsharp#52]
This plugin is great, but at my current job, I'm forced to use the official MS version of FSharp.  Is there a way to run that instead of just mono?  I'm not even wholly opposed to a hackey-ish solution involving Cygwin or symlinks or something...

**Comment by kjnilsson** [comment]
On Windows this will run using .net not mono.

**Comment by Tombert** [comment]
@kjnilsson Ah, the issue might be that be because I'm using the Cygwin version of Vim.  Any chance of that being ported to use the native version?

**Comment by Tombert** [comment]
Is there an environment variable I can set in Cygwin to tell it I'm on windows?

**Comment by kjnilsson** [comment]
Cygwin isn't really supported as it isn't exactly straight forward.  It
needs someone to spend a fair bit of time to get all the path conversions
and whatnot working properly. Contributions in this area are very welcome.
:)

**Comment by Tombert** [comment]
I wouldn't be opposed to adding support for that; in the interim though, do you recommend using GVim or something?

**Comment by kjnilsson** [comment]
Yes GVim is what I have used on windows before. The honest thing to say is
that *nix has had a lot more testing that windows. It should work though.
Raise any issues you find here.

**Comment by Tombert** [comment]
I got things working on a syntax-highlighting level with GVim.  However, when I do `<leader>-t` to grab a type, nothing happens. No errors, no nothing.

**Comment by kjnilsson** [comment]
Has the fsautocomplete backend started? you should be able to see it in task manager.

**Comment by Tombert** [comment]
@kjnilsson It doesn't appear to be running; how do I start it?

**Comment by kjnilsson** [comment]
@Tombert it should start automatically. Can you try the latest version. Make sure you run `install.cmd` after updating.

**Comment by kjnilsson** [comment]
@Tombert I'm closing this. Please re-open if there is still an issue.
