### ISSUE TITLE
No license information

### ISSUE THREAD

**Issue by VPashkov** [fsharp/vim-fsharp#57]
Hi!
Under what license is this project?
I'm curious because i'm making a list of F# tools and want to add license information about each tool.
Is it possible to add a LICENSE.md or something like this to this repository?

**Comment by kjnilsson** [comment]
Hi,

I'm sure we used to have a license but it may have got lost when we moved orgs. I will try to track it down else we'll add another license.

Cheers
Karl

**Comment by kjnilsson** [comment]
Ok added MIT license. Thanks for raising it.

**Comment by VPashkov** [comment]
Thank you!
