### ISSUE TITLE
Syntastic integration doesn't work with latest Syntastic

### ISSUE THREAD

**Issue by Kazark** [fsharp/vim-fsharp#58]
See [this Syntastic issue](https://github.com/scrooloose/syntastic/issues/1893#event-819571541) which was closed in favor of having this plugin updated. Everything else about this plugin still works.

Windows 7
Visual Studio 2008/2010/2013
F# 3.1
Vim 8.0
Latest Syntastic

[This](https://github.com/scrooloose/syntastic/commit/adf899f1ba863b1ea2c3327e7cde79ba21354435) is the commit that introduced the breaking change. Also, the rest of the F# plugin's functionality worked; only it's Syntastic integration didn't work. `:SyntasticInfo` showed that it wasn't working:

```
Syntastic version: 3.7.0-234 (Vim 800, Windows)
Info for filetype: fsharp
Global mode: active
Filetype fsharp is active
The current file will be checked automatically
Available checker: syntax
Currently enabled checkers: -
```

As you can see, the currently enable checkers was disabled.

**Comment by austincrft** [comment]
@kjnilsson Should this be closed because of my #61 or did we want to do more work with enabling errors by default?

**Comment by kjnilsson** [comment]
I'd like to have a little play to see if I can get it to enable automatically first

**Comment by kjnilsson** [comment]
Hmm I'm confused. On my work machine the syntax integration works fine without me setting `let g:syntastic_fsharp_checkers=['syntax']`

**Comment by kjnilsson** [comment]
OK I'm going to close this for now. Please re-open if there are any remaining issues.
