### ISSUE TITLE
Run FsAutoComplete Asynchronously

### ISSUE THREAD

**Issue by austincrft** [fsharp/vim-fsharp#60]
The auto-complete suggestions for this plugin are noticeably slower than [omnisharp-vim](https://github.com/OmniSharp/omnisharp-vim)'s. I imagine the biggest factor in this is how the vim-omnisharp plugin leverages [vim-dispatch](https://github.com/tpope/vim-dispatch) to run the OmniSharp asynchronously.

Do you think this is a desirable feature to implement?

I see there has been a bit of vim-dispatch discussion on issue #13.

**Comment by nosami** [comment]
omnisharp-vim author here :) OmniSharp only uses vim-dispatch to launch the server, it's not used once the server is up and running.

If you use YouCompleteMe with OmniSharp, then completions can be async, but everything else is synchronous.

**Comment by kjnilsson** [comment]
I think the difference here is that the completion server is faster and there won't be much we can do about it until FCS gets faster itself. I'm hoping we can do some exciting things with the async support in vim 8 though. :)

**Comment by nosami** [comment]
@kjnilsson : I haven't tried vim-fsharp in _ages_. Did you ever implement the parse improvements that we talked about?

**Comment by nosami** [comment]
Oh, I remember now. You need background parsing for that to work.

**Comment by kjnilsson** [comment]
@nosami no I just worked around that for now. Given there is no automatic autocompletion (unless you use a plugin) the speed has never bothered me much as I only complete when I need/want.

**Comment by kjnilsson** [comment]
naturally all things may be possible with vim 8 but I feel that may effectively me a re-write

**Comment by austincrft** [comment]
I see what you mean. I use neocomplete, which offers suggestions as I type. It makes the entire editing experience slow, but I suppose I could use only manual completions.

**Comment by kjnilsson** [comment]
Manual completions is all it's been tested for really. I only rarely use them myself. The checker is much more important to me. I will close this for now unless there is something concrete we can address here. (Re-open if so) Making it all async in vim 8 is a whole different project?
