### ISSUE TITLE
build.fsx is very out-of-date

### ISSUE THREAD

**Issue by panesofglass** [fsharp/vim-fsharp#7]
I'm currently trying to resolve this, but it would appear that this tool takes a dependency on FSharp.AutoComplete, which is 1) not available on NuGet and 2) uses paket, whereas this repo uses NuGet.

**Comment by rneatherway** [comment]
Fsharp.autocomplete is available as a binary release on github. I'm not
sure if there is any benefit to providing a nuget package as the consumers
are these other languages for editors and it isn't a library, so unlikely
to be included in other .Net projects.

**Comment by forki** [comment]
Pacakging it as a nuget package will make versioning easier.

**Comment by rneatherway** [comment]
How so? I'm not against it I just haven't seen the benefit yet. It does
look like it would be pretty easy using Paket.

**Comment by forki** [comment]
yes exactly. You would just specify 

    nuget Fsharp.AutoComplete

in your dependencies file and `pakt update` will allow you to keep this thing updated like a lib reference.

We do the same thing with other tools like FAKE, IlRepack, NUnit.Runners and so on.

**Comment by rneatherway** [comment]
I see, I'm not sure if people will want to upgrade versions automatically though. The nuget folder structure is also rather awkward. I saw that @rojepp used an `http` reference: https://github.com/fsharp/sublime-fsharp-package/blob/master/paket.dependencies

These projects are not .NET, so Paket is largely being used to fetch FAKE, which in turn is being used as a cross-platform scripting language (as most of the helpers are not relevant). This is fine, and I am a big fan of both Paket and FAKE, but I don't really see the advantage over e.g. Python in this case. In Emacs I am using a Makefile, which has more sophisticated dependency resolution, but unfortunately isn't well supported on Windows. To test and develop on Windows I am planning to add some (possibly FAKE) script.

**Comment by panesofglass** [comment]
#8 appears to work properly on Windows after setting the relevant settings in my vimrc.

**Comment by forki** [comment]
> I see, I'm not sure if people will want to upgrade versions automatically though

this only happens if you run paket update. So it's not silently updating things in the background.

**Comment by rneatherway** [comment]
OK, thanks for the information, my mistake.
