### ISSUE TITLE
Issues with Eval after 8a7e371

### ISSUE THREAD

**Issue by markwoodhall** [fsharp/vim-fsharp#77]
Hi, thanks for all the work you are doing, still using and loving this plugin. 

I do have a bit of an issue at the moment  though, I've tried to understand what is causing it but I'm not sure. 

All that I know for certain is that after this change https://github.com/fsharp/vim-fsharp/commit/8a7e3712013ca8b648f99e87229944c2b8f19d23 eval'ing anything no longer works for me. It hits the timeout and I get the `....` response. Before that change everything was working fine. 

I'm running neovim on Arch with the neovim python plugin and python version 3.6.0. 

Thanks in advance for any help. 

Cheers.
Mark

**Comment by adityavkk** [comment]
Same problem here

**Comment by kjnilsson** [comment]
Were talking about using the `FsiEval` command? I just tried it on mine and it seems to work ok. Can you get `fsharpi` working ok outside of vim?

**Comment by adityavkk** [comment]
Yeah, `fsharpi` works.

**Comment by kjnilsson** [comment]
@adityavkk are you also using neovim? if so could you try with vim?

**Comment by marcin-wojtowicz** [comment]
I'm running into the same issue here as well.

**Comment by kjnilsson** [comment]
All using neovim?

**Comment by marcin-wojtowicz** [comment]
No, I'm using plain vim.

**Comment by kjnilsson** [comment]
Python3 or 2?

**Comment by marcin-wojtowicz** [comment]
Python 3.

**Comment by randomizedthinking** [comment]
Same here: neovim with python3. Can #78 be merged?

**Comment by kjnilsson** [comment]
I've merged #78 - please can someone test if it improves matters?

**Comment by marcin-wojtowicz** [comment]
It looks like it's working now. Thank you.

**Comment by kjnilsson** [comment]
Thanks to @xuanduc987 for the fix!

**Comment by markwoodhall** [comment]
Working for me now too. Thanks a lot @xuanduc987.
