### ISSUE TITLE
Debian 8 need for vim-python-jedi to be installed

### ISSUE THREAD

**Issue by fedeb95** [fsharp/vim-fsharp#80]
simply installing vim wasn't enough, since `:echo has('python')` or `:echo has('python3')` always returned 0, so failing the execution with rather obscure errors. Installing the package vim-python-jedi solved the issue. This should be stated in the README.

Also the brutal execution of the python interpreter lead to "missing endif" error, and the "#" for python comments not recognized.

**Comment by kjnilsson** [comment]
Hi, thanks for this. I'd welcome a PR with the relevant doc changes for the distribution in question.
