### ISSUE TITLE
Malformed JSON debug message causes Python exception

### ISSUE THREAD

**Issue by randomizedthinking** [fsharp/vim-fsharp#83]
I encountered this strange problem that a python exception is thrown when some fs file is open. After some digging, seems folks in emacs-fsharp-mode discussed it at: https://github.com/fsharp/emacs-fsharp-mode/issues/130. And they had already a solution: https://github.com/fsharp/emacs-fsharp-mode/pull/131.

Can we implement something similar in vim-fsharp? Regards.

**Comment by kjnilsson** [comment]
Thanks for the report, Yes I think we'll have to. I'm a bit strapped for time this week so if anyone would like to submit a PR that would be much appreciated.

**Comment by randomizedthinking** [comment]
Just got a quickfix at #84. The idea is quite simple. Let me know how you think.
