### ISSUE TITLE
Automatically display type of variable when hovering over it. 

### ISSUE THREAD

**Issue by Tombert** [fsharp/vim-fsharp#89]
Hello!  

In the FSharp mode for Emacs, I've become kind of accustomed to being able to simply put my cursor over a variable, and have its type listed on the bottom.  

While I don't mind doing `<leader>t` too much, is there a mechanism to have it automatically display the type?

**Comment by kjnilsson** [comment]
There isn't as syntastic uses the mouseover to display error details. There may be some way to hack it in but it would probably be quite unpleasant.

**Comment by kjnilsson** [comment]
ok I'm closing this for now as unless syntastic supports it we can't.
