### ISSUE TITLE
IOError: [Errpr 32] Broken pipe

### ISSUE THREAD

**Issue by jorge-ortega** [fsharp/vim-fsharp#9]
Installed vim-fsharp with vim-plug. Invoking any syntax or type check command fails with this:

Error detected while processing function fsharpbinding#python#TypeCheck:  
line   14:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/jorge/.vim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 132, in parse
    self.send("parse \"%s\" %s\n" % (fn, fulltext))
  File "/home/jorge/.vim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 93, in send
    self.p.stdin.write(txt)
IOError: [Errno 32] Broken pipe

**Comment by kjnilsson** [comment]
Hi - I don't use vim-plug myself but I suspect that the 'do' command should be 'make' instead of 'make autocomplete'.

Would you be able to try this and see if it works?

**Comment by Vxsery** [comment]
The Plug line now reads

    Plug 'fsharp/vim-fsharp', { 'for' : 'fsharp', 'do' : 'make' }

Still get the same error.

I enabled logging to get some more info. I think there is probably something on my box that may not be letting the plugin communicate with fsautocomplete.

```
> parse "/home/jorge/src/suave/examples/Example/Program.fs" full
.... file goes here ...
> <<EOF>>
msg received None
```
```
> tooltip "/home/jorge/src/suave/examples/Example/Program.fs" 130 10 500
msg received None
```

**Comment by Vxsery** [comment]
So I think I fixed this issue by updating the fsautocomplete version to 0.17.0 in the make file. make clean $$ make to pull it down.

**Comment by Vxsery** [comment]
So that worked for 10 minutes, then same error.

**Comment by kjnilsson** [comment]
how strange - could you give me more info about which version of mono /fsharp you have got installed and which OS you are using?

**Comment by kjnilsson** [comment]
also can you see the completion server processes running?

**Comment by Vxsery** [comment]
```
jorge:~$lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
jorge:~$mono --version
Mono JIT compiler version 4.0.1 (tarball Tue May 12 15:39:23 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
jorge:~$fsharpc
F# Compiler for F# 3.1 (Open Source Edition)
Freely distributed under the Apache 2.0 Open Source License
```
 I can't seem to find the completion server running once I've loaded up an .fs file in vim, which is probably the root cause.

**Comment by kjnilsson** [comment]
yes that sounds like the problem - can you run the fsautocomplete.exe on its own?

**Comment by amazingant** [comment]
I had the same issue @Vxsery originally reported, vim-fsharp installed via pathogen; after getting fsautocomplete.exe running from another tty, I now get:

> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 763, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/home/amazingant/GitHub/dotfiles/vim/bundle/vim-fsharp/ftplugin/fsharpvim.py", line 105, in work
>     parsed = json.loads(data)
>   File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
>     raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded

Posting here because I started with the same error before progressing to this one.

**Comment by kjnilsson** [comment]
Not sure what to best suggest here as I haven't seen this issue myself - even on linux. It does appear that the fsac process isn't started correctly or crashes on start. Could there be some kind of permission issue on the downloaded binaries. The fsac process must be started by vim to work and each instance of vim will start it's own process. If either of you start vim and open an fs or fsx file on a clean system with no other vim instances running - does ps show any mono processes as running?

**Comment by amazingant** [comment]
I know this doesn't help much, but I wiped out the vim-fsharp directory, re-cloned it to the latest master (now with fsautocorrecf 0.18.2) and ran `make` again. Everything works fine now? Guess I'll go back to syntax highlighting.

**Comment by kjnilsson** [comment]
That's great. @Vxsery could you try the latest as well? Cheers.

**Comment by Ghopper21** [comment]
Same issue after installing via Vundle on OS X. When into .vim/bundle/vim-fsharp and did a `make` and the problem disappeared.

**Comment by kjnilsson** [comment]
Sounds like there could be an issue with how these plugin managers install. Not sure as I don't use any of them.

**Comment by kjnilsson** [comment]
@jorge-ortega do we need to keep this issue open?

**Comment by kjnilsson** [comment]
closing due to lack of response. Re-open if needed.
